name: CI/CD for meep backend

on:
workflow_run:
    workflows: ["build-and-push-api"]
    types: [completed]
    branches: [main]
jobs:

  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code
      uses: actions/checkout@v3
    
    - name: Bun Install
      uses: oven-sh/setup-bun@v2

    - run: bun install

  deploy:

    runs-on: ubuntu-latest 

    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            cd /var/www/meep-site/meep-infra       
            docker compose up -d